version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - govet
    - ineffassign
    - misspell
    - nilerr
    - noctx
    - staticcheck
    - unconvert
    - unused

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

