version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: provider
    main: .
    binary: terraform-provider-vappcloud_v{{ .Version }}
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    flags: [-trimpath]
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - id: registry
    ids: [provider]
    formats: [zip]
    name_template: >-
      terraform-provider-vappcloud_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: terraform-provider-vappcloud_{{ .Version }}_SHA256SUMS

signs:
  - artifacts: checksum
    args: ["--batch", "--local-user", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]

sboms:
  - artifacts: archive
    documents:
      - "${artifact}.sbom.spdx.json"

release:
  github:
    owner: vappcloud
    name: vappcloud-terraform-provider
  extra_files:
    - glob: terraform-registry-manifest.json

changelog:
  use: github-native
